import Head from 'next/head'
import { signIn, signOut, useSession } from 'next-auth/client'
import Link from 'next/link'

import styles from '../styles/Home.module.scss'

export default function Home() {
  const [session, loading] = useSession()

  return (
    <div className={styles.wrapper}>
      <header className={styles.header}>
        <div className={styles.login}>
          {!session && (
            <>
              Not signed in <br />
              <button onClick={() => signIn()}>Sign in</button>
            </>
          )}
          {session && (
            <>
              {session.user?.email}
              <button style={{ marginLeft: '.5em' }} onClick={() => signOut()}>
                Sign out
              </button>
            </>
          )}
        </div>
      </header>
      <nav className={styles.nav}>
        <Link href="/timeline">
          <a>Timeline</a>
        </Link>
        <Link href="/transactions">
          <a>My Transaction</a>
        </Link>
      </nav>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
